language: node_js
node_js: 8
os: osx
notifications:  
  email: false
branches:
  only:
    - master
cache:
  - npm
  - directories:
    - "$HOME/.npm"
install:
  - npm install
  - npm -g install serverless@1.38.0
script:
  - npm test
  - npm run lint
after_success:
  - ./travis-deploy.sh
