language: node_js
node_js: 8
notifications:  
  email:  
    recipients:  
      - ${EMAIL} 
    on_success: always  
    on_failure: always
branches:
  only:
    - master
cache:
  - npm
  - directories:
    - "$HOME/.npm"
install:
  - npm -g install serverless
  - npm ci
jobs:
  include:
    - stage: test
      sscript:
      - npm test
      - npm lint
    - stage: deploy
      deploy:
        provider: script
        script: sls deploy --stage prod --force
        on:
          branch: master
