language: node_js
node_js: 8
notifications:  
  email:  
    recipients:  
      - ${EMAIL} 
    on_success: always  
    on_failure: always
branches:
  only:
    - master
cache:
  - npm
  - directories:
    - "$HOME/.npm"
install:
  - npm ci
  - npm -g install serverless
scripts:
  - npm test
  - npm run lint
  - ./travis-deploy.sh
