# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: cave-automation

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

provider:
  name: aws
  runtime: nodejs8.10
  stackName: ${self:custom.stage}-${self:service}
  memorySize: 128
  timeout: 6

plugins:
  - serverless-webpack

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"
#            - "/*"

# you can define service wide environment variables here
#  environment:
#    variable1: value1

# you can add packaging information here
#package:
#  include:
#    - include-me.js
#    - include-me-dir/**
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  tesla:
    handler: handler.getTeslaStatus
    events:
      - schedule: rate(10 minutes)

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.stage}-cave-data
    DataQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.stage}-cave-data-queue
  Outputs:
    NewOutput:
      Description: "Description for the output"
      Value: "Some output value"
