# https://serverless.com/framework/docs/providers/aws/guide/serverless.yml/
service: cave-automation

custom:
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  # todo: move to environment variable file
  dev:
    scheduleEnabled: false
  prod:
    scheduleEnabled: true  

provider:
  name: aws
  runtime: nodejs8.10
  stackName: ${self:custom.stage}-${self:service}
  memorySize: 128
  timeout: 6
  deploymentBucket:
    name: cave-automation-deployment-bucket # manually created bucket

plugins:
  - serverless-webpack

functions:
  tesla:
    handler: handler.getTeslaStatus
    role: arn:aws:iam::550367002470:role/CaveAutomationLambdaRole # manually created role, templating?
    events:
      - schedule:
          rate: rate(10 minutes)
          enabled: ${self:custom.${self:custom.stage}.scheduleEnabled}

resources:
  Resources:
    DataBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.stage}-cave-data
    DataQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: ${self:custom.stage}-cave-data-queue
  Outputs:
    NewOutput:
      Description: "Description for the output"
      Value: "Some output value"
